### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by Ill-Satisfaction** [masterprompt/ModelStitching#6]
There isn't a license present in the repo. Is this intentional?

This is exactly what I'm looking for, but I'm working on a commercial(ish) project right now and I'm unsure what your terms are.

Either way, great work!

**Comment by masterprompt** [comment]
I'll be honest, I didn't think this solution was something that fell under a license..  It was just a solution that I was hoping someone else had come up with but because I didn't find anything out there I was forced to stick all the time/effort into finding a way to do it.  I don't really care who uses it for what purpose as long as they don't try and take this away from anyone else (by claiming it in a restrictive way).  Since this work has been out on the web for years now, and has been date stamped, I don't think anyone has legal claim to it as their own so I feel better knowing anyone can use it as they wish.  If you have a recommendation for a licensing type that I should apply to it that expresses it as I have to you, I'd be happy to add it into the repo.

**Comment by Ill-Satisfaction** [comment]
I think the license that best describes what you're going for is the unlicense:

[https://choosealicense.com/licenses/unlicense/](https://choosealicense.com/licenses/unlicense/)

It's short, to-the-point, and prevents legal issues both with someone trying to claim copyright on your work and with people trying to force liability on you.

Thank you for putting in the time and effort to make this tool, and for being understanding with my need for a license for this project (although I'll take your response as explicit permission for now).

**Comment by masterprompt** [comment]
Added the license, thank you!

**Comment by Ill-Satisfaction** [comment]
Of course! Thank you for being so understanding for an old repo :)
